package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "Voyager")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 7547600296767900486L;
	private int idUser;
	private String userName;
	private String name;
	private String email;
	private String password;
	private UserType userType;
	private Boolean loggedIn;
	private Date createdOn;
	private String createdBy;

	public User() {
	}

	public User(int idUser, String userName, String name, String email, String password, UserType userType, Date createdOn,
			String createdBy) {
		this.idUser = idUser;
		this.userName = userName;
		this.name = name;
		this.email = email;
		this.password = password;
		this.userType = userType;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}
	
	public User(String userName, String name, String email, String password, UserType userType, Date createdOn,	String createdBy) {
		this.userName = userName;
		this.name = name;
		this.email = email;
		this.password = password;
		this.userType = userType;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idUser", unique = true)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "userName", nullable = false, length = 100, unique = true)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "name", nullable = false, length = 155)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToOne
    @JoinColumn(name = "userType", nullable = false)
	public UserType getUserType() {
		return this.userType;
	}

	public void setUserType(UserType userType) {
		this.userType = userType;
	}
	
	@Column(name = "loggedIn", nullable = false)
	public Boolean getLoggedIn() {
		return this.loggedIn;
	}

	public void setLoggedIn(Boolean loggedIn) {
		this.loggedIn = loggedIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "createdBy", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
