package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProject generated by hbm2java
 */
@Entity
@Table(name = "userproject", catalog = "Voyager")
public class UserProject implements java.io.Serializable {

	private static final long serialVersionUID = -5955112472919886603L;
	private int idUserProject;
	private User user;
	private Project project;
	private String projectUserName;
	private String projectPassword;
	private String ruleManagerUserName;
	private String ruleManagerPassword;
	private Date createdOn;
	private String createdBy;

	public UserProject() {
	}

	public UserProject(int idUserProject, User user, Project project, Date createdOn, String createdBy) {
		this.idUserProject = idUserProject;
		this.user = user;
		this.project = project;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public UserProject(int idUserProject, User user, Project project, String projectUserName, String projectPassword,
			String ruleManagerUserName, String ruleManagerPassword, Date createdOn, String createdBy) {
		this.idUserProject = idUserProject;
		this.user = user;
		this.project = project;
		this.projectUserName = projectUserName;
		this.projectPassword = projectPassword;
		this.ruleManagerUserName = ruleManagerUserName;
		this.ruleManagerPassword = ruleManagerPassword;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}
	
	public UserProject(User user, Project project, String projectUserName, String projectPassword,
			String ruleManagerUserName, String ruleManagerPassword, Date createdOn, String createdBy) {
		this.user = user;
		this.project = project;
		this.projectUserName = projectUserName;
		this.projectPassword = projectPassword;
		this.ruleManagerUserName = ruleManagerUserName;
		this.ruleManagerPassword = ruleManagerPassword;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idUserProject", unique = true, nullable = false)
	public int getIdUserProject() {
		return this.idUserProject;
	}

	public void setIdUserProject(int idUserProject) {
		this.idUserProject = idUserProject;
	}
	
	@OneToOne
    @JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	@OneToOne
    @JoinColumn(name = "project", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "projectUserName", length = 100)
	public String getProjectUserName() {
		return this.projectUserName;
	}

	public void setProjectUserName(String projectUserName) {
		this.projectUserName = projectUserName;
	}

	@Column(name = "projectPassword", length = 100)
	public String getProjectPassword() {
		return this.projectPassword;
	}

	public void setProjectPassword(String projectPassword) {
		this.projectPassword = projectPassword;
	}

	@Column(name = "ruleManagerUserName", length = 100)
	public String getRuleManagerUserName() {
		return this.ruleManagerUserName;
	}

	public void setRuleManagerUserName(String ruleManagerUserName) {
		this.ruleManagerUserName = ruleManagerUserName;
	}

	@Column(name = "ruleManagerPassword", length = 100)
	public String getRuleManagerPassword() {
		return this.ruleManagerPassword;
	}

	public void setRuleManagerPassword(String ruleManagerPassword) {
		this.ruleManagerPassword = ruleManagerPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "createdBy", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
