package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "Voyager")
public class Project implements java.io.Serializable {

	private int idProject;
	private String name;
	private int bugSystem;
	private Integer ruleManager;
	private Date createdOn;
	private String createdBy;

	public Project() {
	}

	public Project(int idProject, String name, int bugSystem, Date createdOn, String createdBy) {
		this.idProject = idProject;
		this.name = name;
		this.bugSystem = bugSystem;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Project(int idProject, String name, int bugSystem, Integer ruleManager, Date createdOn, String createdBy) {
		this.idProject = idProject;
		this.name = name;
		this.bugSystem = bugSystem;
		this.ruleManager = ruleManager;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "idProject", unique = true, nullable = false)
	public int getIdProject() {
		return this.idProject;
	}

	public void setIdProject(int idProject) {
		this.idProject = idProject;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "bugSystem", nullable = false)
	public int getBugSystem() {
		return this.bugSystem;
	}

	public void setBugSystem(int bugSystem) {
		this.bugSystem = bugSystem;
	}

	@Column(name = "ruleManager")
	public Integer getRuleManager() {
		return this.ruleManager;
	}

	public void setRuleManager(Integer ruleManager) {
		this.ruleManager = ruleManager;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "createdBy", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
