package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BugSystem generated by hbm2java
 */
@Entity
@Table(name = "bugsystem", catalog = "Voyager")
public class BugSystem implements java.io.Serializable {

	private static final long serialVersionUID = -6787730676406890862L;
	private int idBugSystem;
	private String name;
	private String url;
	private BugSystemType bugSystemType;
	private Date createdOn;
	private String createdBy;

	public BugSystem() {
	}

	public BugSystem(int idBugSystem, String name, String url, BugSystemType bugSystemType, Date createdOn, String createdBy) {
		this.idBugSystem = idBugSystem;
		this.name = name;
		this.url = url;
		this.bugSystemType = bugSystemType;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}
	
	public BugSystem(String name, String url, BugSystemType bugSystemType, Date createdOn, String createdBy) {
		this.name = name;
		this.url = url;
		this.bugSystemType = bugSystemType;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idBugSystem", unique = true, nullable = false)
	public int getIdBugSystem() {
		return this.idBugSystem;
	}

	public void setIdBugSystem(int idBugSystem) {
		this.idBugSystem = idBugSystem;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@OneToOne
    @JoinColumn(name = "bugSystemType", nullable = false)
	public BugSystemType getBugSystemType() {
		return this.bugSystemType;
	}

	public void setBugSystemType(BugSystemType bugSystemType) {
		this.bugSystemType = bugSystemType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "createdBy", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
