package com.voyagerproject.model;
// Generated Feb 27, 2016 12:34:42 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RuleManagerType generated by hbm2java
 */
@Entity
@Table(name = "rulemanagertype", catalog = "Voyager")
public class RuleManagerType implements java.io.Serializable {

	private static final long serialVersionUID = -377773422443526541L;
	private int idRuleManagerType;
	private String name;
	private Date createdOn;
	private String createdBy;

	public RuleManagerType() {
	}

	public RuleManagerType(int idRuleManagerType, String name, Date createdOn, String createdBy) {
		this.idRuleManagerType = idRuleManagerType;
		this.name = name;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "idRuleManagerType", unique = true, nullable = false)
	public int getIdRuleManagerType() {
		return this.idRuleManagerType;
	}

	public void setIdRuleManagerType(int idRuleManagerType) {
		this.idRuleManagerType = idRuleManagerType;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 19, insertable = false)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "createdBy", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
