package com.voyagerproject.model;
// Generated Feb 28, 2016 12:50:47 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "usertype", catalog = "Voyager")
public class UserType implements java.io.Serializable {

	private int idUserType;
	private String name;
	private Date createdOn;
	private String createdBy;

	public UserType() {
	}

	public UserType(int idUserType, String name, Date createdOn, String createdBy) {
		this.idUserType = idUserType;
		this.name = name;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "idUserType", unique = true, nullable = false)
	public int getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(int idUserType) {
		this.idUserType = idUserType;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Transient
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "createdBy", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
